import { Inter } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

import "./globals.css";
import Header from '@/components/Header'
import  ThemeProvider from '@/providers/ThemeProvider'

import type { Metadata } from "next";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MonoPage",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  const messages = await getMessages()
 
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Header />
        <NextIntlClientProvider messages={messages}>
      {children}
      </NextIntlClientProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
