import { Inter } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl'
import {getTranslations} from 'next-intl/server';
import { getMessages } from 'next-intl/server'

import "./globals.css";
import Header from '@/components/Header'
import Footer from "@/components/Footer";
import ThemeProvider from '@/providers/ThemeProvider'
import type { Metadata } from "next";
import StickyScrollToTopButton from '@/components/StickyScrollToTopButton'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MonoPage",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  const messages = await getMessages()
  const tStickyScrollToTopButton = await getTranslations('Components.StickyScrollToTopButton')

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <Header />
              {children}
            <Footer />
            <StickyScrollToTopButton 
            StickyScrollToTopButton={tStickyScrollToTopButton('scrollToTop')} 
            />
</NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}